### PR TITLE
squashed apps veto-app into maintenance-app

### PR DESCRIPTION
**Pull request by Gfloresechaiz**
I've squashed everything veto-app into maintenance-app that was missing except : 

/layouts since I don't see the point to have the sidebar for now
/components/sidebar since it gave a weird typing bug (however we won't use it for now) 

I squashed a bit of the dashboard page to include the dark style button and styled the heading.

renamed maintenance-frontend to dashboard-frontend, same for backend. 

renamed yarn start:maintenance to yarn start:dashboard.

I'll need to make updates on the READMEs but that should be it.

### CODE REVIEW

**Comment by drawm** [comment]
Build is failing due to a missing maintenance => dashboard 
https://travis-ci.com/github/Veriphi/veto/jobs/366942754
```
FAIL  packages/maintenance-app/backend/src/scripts/__tests__/getApplicationState.spec.ts

  ● Test suite failed to run

    packages/maintenance-app/backend/src/scripts/__tests__/getApplicationState.spec.ts:3:41 - error TS2307: Cannot find module '@maintenance-app/types/src' or its corresponding type declarations.

    3 import { ApplicationState, State } from '@maintenance-app/types/src'

                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Gfloresechaiz** [comment]
ok made a commit that should fix that issue

**Comment by Gfloresechaiz** [comment]
I have another PR (spark and green features on frontend) but I'll wait for this one to be approved so changes don't appear twice.

**Comment by Gfloresechaiz** [comment]
made a last commit to fix the CI failure

**Pull request merged**
